INSERT INTO silem.menu(
            pkmenu, title, icon_class, icon_code, router_url, fkmenu)
            VALUES

(1,'Inicial','material-icons','dashboard','/main/dashboard',null),
(2,'Câmara','material-icons','people',null,null),
(3,'Protocolo','material-icons',null,null,2),
(4,'Licitação','material-icons',null,null,2),
(15,'Chamado','material-icons',null,null,2),
(19,'Inventário','material-icons',null,null,2),
(23,'Servidor','material-icons',null,null,2),
(27,'UVC',null,null,null,2),
(28,'Institucional','material-icons','location_city',null,null),
(29,'Lista de Presidentes',null,null,null,28),
(30,'Lei Municipal',null,null,null,28),
(31,'Regimento Interno',null,null,null,28),
(32,'Agenda de Eventos','material-icons','date_range',null,null),
(33,'Atendimento Público',null,null,null,32),
(34,'Dúvidas',null,null,null,32),
(35,'Eventos',null,null,null,32),
(37,'Vereadores','material-icons','face',null,null),
(38,'Cadastrar','material-icons','keyboard_arrow_right',null,37),
(39,'Vereador',null,null,'/main/vereadores/vereador',38),
(41,'Partido',null,null,'/main/vereadores/partido',38),
(42,'Mandato',null,null,'/main/vereadores/mandato',38),
(43,'Mesa Diretora',null,null,null,38),
(44,'Comissões',null,null,'/main/vereadores/vereador-comissao',38),
(45,'Preposições',null,null,null,38),
(46,'Relatorias',null,null,null,38),
(47,'Proposições',null,null,null,37),
(49,'Atividades Legislativas','material-icons','account_balance',null,null),
(50,'Plenário','material-icons','keyboard_arrow_right',null,49),
(52,'Expediente',null,null,'/main/legislativas/expediente',50),
(53,'Comissões',null,null,'/main/legislativas/comissao',49),
(57,'Oradores','material-icons','keyboard_arrow_right',null,49),
(61,'Transparência','material-icons','info',null,null),
(62,'Serviços','material-icons','work',null,null),
(63,'Empresas','material-icons','keyboard_arrow_right',null,62),
(67,'Legislatura',null,null,'/main/camara/legislatura',2),
(68,'Tipo de Registro',null,null,'/main/camara/tipo-registro',2),
(69,'Cargo',null,null,'/main/vereadores/cargo',38),
(70,'Calendário',null,null,'/main/camara/calendario',2),
(71,'Cadastrar',null,null,'/main/legislativas/cadastrar-orador',57),
(72,'Por Sessão',null,null,'/main/legislativas/oradores-sessao',57),
(73,'Plenária',null,null,'/main/legislativas/plenaria',50),
(74,'Requerimento',null,null,'/main/legislativas/requerimento',50),
(76,'Vereador/Partido',null,null,'/main/vereadores/vereador-partido',38)
